---
title: "ENV 872 Final Project Data Exploration"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

``` {r Establish Working Directory, warning=FALSE, echo=FALSE, include=FALSE}
library(lubridate)
library(ggplot2)
library(mapview)
library(tidyverse)
library(here)
library(ggthemes)
library(RColorBrewer)
library(sf)
library(leaflet)

here()
```

``` {r Set Environment}
Ambient_Noise <- read.csv(here("Data/Processed/Ambient_Grouped.csv"))
Hemlock_Condition <- read.csv(here("Data/Processed/Hemlock_Grouped.csv"))
Road_Noise <- read.csv(here("Data/Processed/Road_Grouped.csv"))
Woodpeckers_Grouped <- read.csv(here("Data/Processed/Woodpeckers_Grouped.csv"))
# For Presence/Nonpresence
Woodpeckers_Delaware <- read.csv(here("Data/Processed/Woodpeckers_Delaware.csv"))
# Comprehensive
Woodpeckers_Date <- read.csv(here("Data/Processed/Dateincluded_Woodpeckers.csv"))
Woodpeckers_Date$Detection_Date <- ymd(Woodpeckers_Date$Detection_Date)

```

``` {r Set Theme}
TheTheme <- theme_solarized(base_size = 12) +
  theme(axis.text = element_text(color="black"),
                              legend.position = "right",
                              legend.text = element_text(size = 8, color = "black"),
                              legend.title = element_text(size = 10, color = "black", face = "bold"),
                              axis.title = element_text(size = 10, color = "black", face = "bold"),
                              plot.title = element_text(size = 11, color = "black", face = "bold"),
                              )
theme_set(TheTheme)

```

``` {r Table of Woodpecker Appearance per Year}
Woodpeckers_GroupedTrim <- Woodpeckers_Grouped %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Total_Detections = sum(Detection_Count))
  
summary(Woodpeckers_GroupedTrim$Total_Detections)

```

``` {r / Line Plot of Species Appearance Over Time}
Species_over_time <- 
  ggplot(Woodpeckers_GroupedTrim, 
         aes(x=Year,
             y=Total_Detections,
             color=Common_Name)) +
  geom_line() +
  labs(
    x="Year",
    y="Number of Detections",
    title="Woodpecker Species Appearance (2014-2025)",
    color="Species") +
  scale_x_continuous(breaks=seq(2015,2025, by=2))
Species_over_time + scale_color_brewer(palette="Dark2")

```

``` {r Ambient Noise Averages}
Ambient_Noise_Average <- Ambient_Noise %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Average_Noise = mean(Ambient_Noise))
  
summary(Ambient_Noise_Average$Average_Noise)

```

``` {r / Scatter Plot of Ambient Noise Over Time}
Noise_over_time <- 
  ggplot(Woodpeckers_Date,
         aes(x=Detection_Date,
             y=Ambient_Noise,
             color=Common_Name)) +
  geom_point() +
  labs(
    x="Date",
    y="Ambient Noise (dB)",
    title="Ambient Noise Levels (2014-2025)",
    color="Species") +
  scale_x_date(date_breaks = "2 year", date_labels = "%Y") +
  scale_y_continuous(breaks = c(30, 35, 40, 45, 50, 55, 60, 65)) +
  geom_smooth(method = lm, se = FALSE, size = 0.5)

Noise_over_time + scale_color_brewer(palette="Dark2")

```

``` {r Line Plot of Average Ambient Noise}
AverageAmbientPlot <-
  ggplot(Ambient_Noise_Average,
         aes(x=Year,
             y=Average_Noise,
             color=Common_Name)) +
  geom_line() +
  labs(
    x="Year",
    y="Average Ambient Noise (dB)",
    title="Average Ambient Noise Levels (2014-2025)",
    color="Species") +
  scale_y_continuous(breaks = seq(36,52, by=2)) +
  scale_x_continuous(breaks=seq(2015,2025, by=2))

AverageAmbientPlot + scale_color_brewer(palette="Dark2")

```

``` {r Road Noise Proportions}
RoadNoiseProportionPerYear <- Road_Noise %>% 
  select(c(Year:Detection_Count)) %>% 
  group_by(Year, Road_Noise, Common_Name) %>% 
  summarise(Count = sum(Detection_Count))

RoadNoisePlot <- 
  ggplot(RoadNoiseProportionPerYear,
         aes(fill = Common_Name,
             y = Count,
             x = Year)) +
  geom_bar(position = "stack", stat = "identity") + 
  facet_wrap(~Road_Noise) +
  scale_x_continuous(breaks=seq(2015,2025, by=2)) +
  labs(x = "Year",
       y = "Observation Count",
       title = "Road Noise Presence per Observation (2014-2025)",
       fill = "Species") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
RoadNoisePlot + scale_fill_brewer(palette="Dark2")

```

``` {r Hemlock Average per Year}
Hemlock_Score_Average <- Hemlock_Condition %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Average_Hemlock = mean(Hemlock_Condition_Score))

```

``` {r / Line Plot or Scatter Plot of Hemlock Condition Over Time}
Hemlock_over_time <-
  ggplot(Hemlock_Score_Average,
         aes(x=Year,
             y=Average_Hemlock,
             color=Common_Name)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE, size = 0.5) +
  scale_x_continuous(breaks = seq(2015,2025, by = 2)) +
  scale_y_continuous(breaks = seq(0,5, by = 1)) +
  labs(title = "Average Hemlock Score for All Sites (2014-2025)",
       x = "Year",
       y = "Average Hemlock Score",
       color = "Species")
  
Hemlock_over_time + scale_color_brewer(palette="Dark2")

```


``` {r / Graph Monitoring Sites}
ObservationSites <- Woodpeckers_Delaware %>% 
  st_as_sf( coords = c('Longitude','Latitude'), 
    crs=4326
    )

MonitoringSites <- mapview(ObservationSites, 
        cex = 4,
        col.regions = "firebrick",
        layer.name = "Observation Sites",
        map.types = c("Esri.NatGeoWorldMap", "CartoDB.Positron", "Esri.WorldImagery")) 
MonitoringSites

```

``` {r Plot Species Observation Spatially}
Ambient_Noise_AveragePerSite <- Woodpeckers_Date %>% 
  select(c(Detection_Date:Longitude)) %>% 
  group_by(Latitude, Longitude) %>% 
  summarise(Average_Noise = mean(Ambient_Noise))
  
summary(Ambient_Noise_Average$Average_Noise)

AverageNoisePerSiteSF <-Ambient_Noise_AveragePerSite %>% 
   st_as_sf( coords = c('Longitude','Latitude'), 
    crs=4326
    )

---
  
Hemlock_

MonitoringSitesNoise <- mapview(AverageNoisePerSiteSF, 
        zcol = 'Average_Noise',
        alpha.regions = 0.4,
        layer.name = "Ambient Noise Level",
        map.types = c("Esri.NatGeoWorldMap", "CartoDB.Positron", "Esri.WorldImagery")) 
AllVariablesMapview <- mapview(MonitoringSitesNoise) +
  mapview()

```
