---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r, packages, working directory}

library(tidyverse)
library (lubridate)
library(here)
library(ggplot2)

here()
getwd()

```


```{r, import the raw data csv}

pointcount_detection <- read.csv(file = here("Data","Raw","ERMN_StreamsideBirds_2315071_PointCount.csv"))

```

```{r, change date objects and create year column}

pointcount_detection$Start_Date_ISO <- ymd(pointcount_detection$Start_Date_ISO)
class(pointcount_detection$Start_Date_ISO)

pointcount_detection <- pointcount_detection %>%
  mutate(Year = year(Start_Date_ISO))

```

```{r, select columns of interest}

pointcount_detection_trim <- select(pointcount_detection,
                          Unit_Code,
                          Site_Name,
                          Year,
                          Ambient_Noise,
                          Road_Noise,
                          Common_Name,
                          Hemlock_Condition_Score,
                          Latitude,
                          Longitude
                          )

```

```{r, get rid of unidentified or absent birds, 839 unidentified and 25 no birds spotted}

detection_final <- pointcount_detection_trim %>%
  filter(!Common_Name %in% c("Unidentified Bird",
                             "Unidentified Woodpecker",
                             "Not Applicable"))

```

```{r, filter dataframe for only woodpeckers in the Delaware River Gap}

woodpeckers_delaware <- detection_final %>%
  filter(Common_Name %in% c("Downy Woodpecker",
                            "Pileated Woodpecker",
                            "Red-bellied Woodpecker",
                            "Hairy Woodpecker")) %>%
  filter(Unit_Code %in% c("DEWA"))
                   
```

```{r, changing column name for clarity}
woodpeckers_delaware <-woodpeckers_delaware %>%
  rename(National_Park = Unit_Code)

```


```{r, group by site name, year, and common name}
woodpeckers_grouped <-woodpeckers_delaware %>%
  group_by(Site_Name,Year, Common_Name) %>%
  summarise(Detection_Count = n())

```


```{r, group by site name, year, common name and then the possible explanatory variables (ambient noise, road noise, and hemlock condition)}

ambient_grouped <- woodpeckers_delaware %>%
  group_by(Site_Name,Year, Common_Name, Ambient_Noise) %>%
  summarise(Detection_Count = n())

road_grouped <- woodpeckers_delaware %>%
  group_by(Site_Name,Year, Common_Name, Road_Noise) %>%
  summarise(Detection_Count = n())

hemlock_grouped <- woodpeckers_delaware %>%
  group_by(Site_Name,Year, Common_Name, Hemlock_Condition_Score) %>%
  summarise(Detection_Count = n())

```


```{r, place the processed dataset into the processed folder}

write.csv(woodpeckers_delaware, row.names = FALSE, 
          file = here("Data","Processed","Woodpeckers_Delaware.csv"))

write.csv(woodpeckers_grouped, row.names = FALSE, 
          file = here("Data","Processed","Woodpeckers_Grouped.csv"))

write.csv(ambient_grouped, row.names = FALSE, 
          file = here("Data","Processed","Ambient_Grouped.csv"))

write.csv(road_grouped, row.names = FALSE, 
          file = here("Data","Processed","Road_Grouped.csv"))

write.csv(hemlock_grouped, row.names = FALSE, 
          file = here("Data","Processed","Hemlock_Grouped.csv"))

```


```{r}
dateincluded_trim <- select(pointcount_detection,
                          Unit_Code,
                          Site_Name,
                          Start_Date_ISO,
                          Year,
                          Ambient_Noise,
                          Road_Noise,
                          Common_Name,
                          Hemlock_Condition_Score,
                          Latitude,
                          Longitude
                          )

dateincluded_woodpeckers <- dateincluded_trim %>%
  filter(!Common_Name %in% c("Unidentified Bird",
                             "Unidentified Woodpecker",
                             "Not Applicable")) %>%
  filter(Common_Name %in% c("Downy Woodpecker",
                            "Pileated Woodpecker",
                            "Red-bellied Woodpecker",
                            "Hairy Woodpecker")) %>%
  filter(Unit_Code %in% c("DEWA"))%>%
  rename(National_Park = Unit_Code) %>%
  rename(Detection_Date = Start_Date_ISO)

```

```{r}
write.csv(dateincluded_woodpeckers, row.names = FALSE, 
          file = here("Data","Processed","Dateincluded_Woodpeckers.csv"))
```


```{r Woodpecker Species Appearance Per Year and Per Site}
 
detections_per_year <- woodpeckers_grouped %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Total_Detections = sum(Detection_Count))

sites_observations_XY <- woodpeckers_delaware %>%
  select(Site_Name,Latitude,Longitude)%>%
  group_by(Site_Name,Latitude,Longitude)%>%
  summarise(total_detections = n())

sites_observations_XY_species <- woodpeckers_delaware %>%
  select(Site_Name,Latitude,Longitude,Common_Name)%>%
  group_by(Site_Name,Latitude,Longitude,Common_Name)%>%
  summarise(total_detections = n())

```

```{r Average Ambient Noise Per Year}

ambient_noise_average <- ambient_grouped %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Average_Noise = mean(Ambient_Noise))

ambient_noise_averagepersite <- woodpeckers_delaware %>% 
  select(c(Detection_Date:Longitude)) %>% 
  group_by(Latitude, Longitude) %>% 
  summarise(Average_Noise = mean(Ambient_Noise))

```

```{r Average Hemlock Per Site}

hemlock_average_XY <- woodpeckers_delaware %>%
  select(Site_Name,Hemlock_Condition_Score,Latitude,Longitude)%>%
  group_by(Site_Name, Latitude, Longitude)%>%
  summarise(Average_Hemlock_Score = mean(Hemlock_Condition_Score))

hemlock_score_average <- hemlock_grouped %>% 
  select(c(Year:Detection_Count)) %>% 
  arrange(Year, Common_Name) %>% 
  group_by(Year, Common_Name) %>% 
  summarise(Average_Hemlock = mean(Hemlock_Condition_Score))

```

```{r Road Noise Presence Per Site, Road Noise Proportion Per Year}

road_noise_false_XY <- woodpeckers_delaware %>%
  filter(Road_Noise == "FALSE")%>%
  select(Site_Name,Road_Noise,Latitude,Longitude)%>%
  distinct(Site_Name, Latitude, Longitude)

road_noise_true_XY <- woodpeckers_delaware %>%
  filter(Road_Noise == "TRUE")%>%
  select(Site_Name,Road_Noise,Latitude,Longitude)%>%
  distinct(Site_Name, Latitude, Longitude)

roadnoiseproportionperyear <- road_grouped %>% 
  select(c(Year:Detection_Count)) %>% 
  group_by(Year, Road_Noise, Common_Name) %>% 
  summarise(Count = sum(Detection_Count))

```


```

